[package]
name = "honest_sign"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
dotenv = "0.15.0"
google-sheets4 = "6.0.0"
hyper = { version = "1.7.0", features = ["full"] }
hyper-rustls = { version = "0.27.7" }
hyper-util = { version = "0.1.17", features = ["full"] }
lopdf = "0.38.0"
rustls = { version = "0.23.32", features = ["aws-lc-rs"] }
tokio = { version = "1.47.1", features = ["full"] }
